module StripeAPI.Types.BotCommandScopeAllPrivateChats where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data BotCommandScopeAllPrivateChats
instance Show BotCommandScopeAllPrivateChats
instance Eq BotCommandScopeAllPrivateChats
instance FromJSON BotCommandScopeAllPrivateChats
instance ToJSON BotCommandScopeAllPrivateChats
