module StripeAPI.Types.BotCommandScopeAllChatAdministrators where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data BotCommandScopeAllChatAdministrators
instance Show BotCommandScopeAllChatAdministrators
instance Eq BotCommandScopeAllChatAdministrators
instance FromJSON BotCommandScopeAllChatAdministrators
instance ToJSON BotCommandScopeAllChatAdministrators
