-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema BotCommandScopeAllGroupChats
module StripeAPI.Types.BotCommandScopeAllGroupChats where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.BotCommandScopeAllGroupChats@ in the specification.
-- 
-- Represents the [scope](https:\/\/core.telegram.org\/bots\/api\/\#botcommandscope) of bot commands, covering all group and supergroup chats.
data BotCommandScopeAllGroupChats = BotCommandScopeAllGroupChats {
  -- | type: Scope type, must be *all\\_group\\_chats*
  botCommandScopeAllGroupChatsType :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON BotCommandScopeAllGroupChats
    where toJSON obj = Data.Aeson.Types.Internal.object ("type" Data.Aeson.Types.ToJSON..= botCommandScopeAllGroupChatsType obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("type" Data.Aeson.Types.ToJSON..= botCommandScopeAllGroupChatsType obj)
instance Data.Aeson.Types.FromJSON.FromJSON BotCommandScopeAllGroupChats
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "BotCommandScopeAllGroupChats" (\obj -> GHC.Base.pure BotCommandScopeAllGroupChats GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))
-- | Create a new 'BotCommandScopeAllGroupChats' with all required fields.
mkBotCommandScopeAllGroupChats :: Data.Text.Internal.Text -- ^ 'botCommandScopeAllGroupChatsType'
  -> BotCommandScopeAllGroupChats
mkBotCommandScopeAllGroupChats botCommandScopeAllGroupChatsType = BotCommandScopeAllGroupChats{botCommandScopeAllGroupChatsType = botCommandScopeAllGroupChatsType}
