-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PassportElementErrorTranslationFiles
module StripeAPI.Types.PassportElementErrorTranslationFiles where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.PassportElementErrorTranslationFiles@ in the specification.
-- 
-- Represents an issue with the translated version of a document. The error is considered resolved when a file with the document translation change.
data PassportElementErrorTranslationFiles = PassportElementErrorTranslationFiles {
  -- | file_hashes: List of base64-encoded file hashes
  passportElementErrorTranslationFilesFileHashes :: ([Data.Text.Internal.Text])
  -- | message: Error message
  , passportElementErrorTranslationFilesMessage :: Data.Text.Internal.Text
  -- | source: Error source, must be *translation\\_files*
  , passportElementErrorTranslationFilesSource :: Data.Text.Internal.Text
  -- | type: Type of element of the user\'s Telegram Passport which has the issue, one of “passport”, “driver\\_license”, “identity\\_card”, “internal\\_passport”, “utility\\_bill”, “bank\\_statement”, “rental\\_agreement”, “passport\\_registration”, “temporary\\_registration”
  , passportElementErrorTranslationFilesType :: PassportElementErrorTranslationFilesType'
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PassportElementErrorTranslationFiles
    where toJSON obj = Data.Aeson.Types.Internal.object ("file_hashes" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesFileHashes obj : "message" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesMessage obj : "source" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesSource obj : "type" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesType obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("file_hashes" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesFileHashes obj) GHC.Base.<> (("message" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesMessage obj) GHC.Base.<> (("source" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesSource obj) GHC.Base.<> ("type" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFilesType obj))))
instance Data.Aeson.Types.FromJSON.FromJSON PassportElementErrorTranslationFiles
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PassportElementErrorTranslationFiles" (\obj -> (((GHC.Base.pure PassportElementErrorTranslationFiles GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_hashes")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "message")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "source")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))
-- | Create a new 'PassportElementErrorTranslationFiles' with all required fields.
mkPassportElementErrorTranslationFiles :: [Data.Text.Internal.Text] -- ^ 'passportElementErrorTranslationFilesFileHashes'
  -> Data.Text.Internal.Text -- ^ 'passportElementErrorTranslationFilesMessage'
  -> Data.Text.Internal.Text -- ^ 'passportElementErrorTranslationFilesSource'
  -> PassportElementErrorTranslationFilesType' -- ^ 'passportElementErrorTranslationFilesType'
  -> PassportElementErrorTranslationFiles
mkPassportElementErrorTranslationFiles passportElementErrorTranslationFilesFileHashes passportElementErrorTranslationFilesMessage passportElementErrorTranslationFilesSource passportElementErrorTranslationFilesType = PassportElementErrorTranslationFiles{passportElementErrorTranslationFilesFileHashes = passportElementErrorTranslationFilesFileHashes,
                                                                                                                                                                                                                                                             passportElementErrorTranslationFilesMessage = passportElementErrorTranslationFilesMessage,
                                                                                                                                                                                                                                                             passportElementErrorTranslationFilesSource = passportElementErrorTranslationFilesSource,
                                                                                                                                                                                                                                                             passportElementErrorTranslationFilesType = passportElementErrorTranslationFilesType}
-- | Defines the enum schema located at @components.schemas.PassportElementErrorTranslationFiles.properties.type@ in the specification.
-- 
-- Type of element of the user\'s Telegram Passport which has the issue, one of “passport”, “driver\\_license”, “identity\\_card”, “internal\\_passport”, “utility\\_bill”, “bank\\_statement”, “rental\\_agreement”, “passport\\_registration”, “temporary\\_registration”
data PassportElementErrorTranslationFilesType' =
   PassportElementErrorTranslationFilesType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PassportElementErrorTranslationFilesType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PassportElementErrorTranslationFilesType'EnumPassport -- ^ Represents the JSON value @"passport"@
  | PassportElementErrorTranslationFilesType'EnumDriverLicense -- ^ Represents the JSON value @"driver_license"@
  | PassportElementErrorTranslationFilesType'EnumIdentityCard -- ^ Represents the JSON value @"identity_card"@
  | PassportElementErrorTranslationFilesType'EnumInternalPassport -- ^ Represents the JSON value @"internal_passport"@
  | PassportElementErrorTranslationFilesType'EnumUtilityBill -- ^ Represents the JSON value @"utility_bill"@
  | PassportElementErrorTranslationFilesType'EnumBankStatement -- ^ Represents the JSON value @"bank_statement"@
  | PassportElementErrorTranslationFilesType'EnumRentalAgreement -- ^ Represents the JSON value @"rental_agreement"@
  | PassportElementErrorTranslationFilesType'EnumPassportRegistration -- ^ Represents the JSON value @"passport_registration"@
  | PassportElementErrorTranslationFilesType'EnumTemporaryRegistration -- ^ Represents the JSON value @"temporary_registration"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PassportElementErrorTranslationFilesType'
    where toJSON (PassportElementErrorTranslationFilesType'Other val) = val
          toJSON (PassportElementErrorTranslationFilesType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (PassportElementErrorTranslationFilesType'EnumPassport) = "passport"
          toJSON (PassportElementErrorTranslationFilesType'EnumDriverLicense) = "driver_license"
          toJSON (PassportElementErrorTranslationFilesType'EnumIdentityCard) = "identity_card"
          toJSON (PassportElementErrorTranslationFilesType'EnumInternalPassport) = "internal_passport"
          toJSON (PassportElementErrorTranslationFilesType'EnumUtilityBill) = "utility_bill"
          toJSON (PassportElementErrorTranslationFilesType'EnumBankStatement) = "bank_statement"
          toJSON (PassportElementErrorTranslationFilesType'EnumRentalAgreement) = "rental_agreement"
          toJSON (PassportElementErrorTranslationFilesType'EnumPassportRegistration) = "passport_registration"
          toJSON (PassportElementErrorTranslationFilesType'EnumTemporaryRegistration) = "temporary_registration"
instance Data.Aeson.Types.FromJSON.FromJSON PassportElementErrorTranslationFilesType'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "passport" -> PassportElementErrorTranslationFilesType'EnumPassport
                                            | val GHC.Classes.== "driver_license" -> PassportElementErrorTranslationFilesType'EnumDriverLicense
                                            | val GHC.Classes.== "identity_card" -> PassportElementErrorTranslationFilesType'EnumIdentityCard
                                            | val GHC.Classes.== "internal_passport" -> PassportElementErrorTranslationFilesType'EnumInternalPassport
                                            | val GHC.Classes.== "utility_bill" -> PassportElementErrorTranslationFilesType'EnumUtilityBill
                                            | val GHC.Classes.== "bank_statement" -> PassportElementErrorTranslationFilesType'EnumBankStatement
                                            | val GHC.Classes.== "rental_agreement" -> PassportElementErrorTranslationFilesType'EnumRentalAgreement
                                            | val GHC.Classes.== "passport_registration" -> PassportElementErrorTranslationFilesType'EnumPassportRegistration
                                            | val GHC.Classes.== "temporary_registration" -> PassportElementErrorTranslationFilesType'EnumTemporaryRegistration
                                            | GHC.Base.otherwise -> PassportElementErrorTranslationFilesType'Other val)
