-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PassportElementErrorTranslationFile
module StripeAPI.Types.PassportElementErrorTranslationFile where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.PassportElementErrorTranslationFile@ in the specification.
-- 
-- Represents an issue with one of the files that constitute the translation of a document. The error is considered resolved when the file changes.
data PassportElementErrorTranslationFile = PassportElementErrorTranslationFile {
  -- | file_hash: Base64-encoded file hash
  passportElementErrorTranslationFileFileHash :: Data.Text.Internal.Text
  -- | message: Error message
  , passportElementErrorTranslationFileMessage :: Data.Text.Internal.Text
  -- | source: Error source, must be *translation\\_file*
  , passportElementErrorTranslationFileSource :: Data.Text.Internal.Text
  -- | type: Type of element of the user\'s Telegram Passport which has the issue, one of “passport”, “driver\\_license”, “identity\\_card”, “internal\\_passport”, “utility\\_bill”, “bank\\_statement”, “rental\\_agreement”, “passport\\_registration”, “temporary\\_registration”
  , passportElementErrorTranslationFileType :: PassportElementErrorTranslationFileType'
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PassportElementErrorTranslationFile
    where toJSON obj = Data.Aeson.Types.Internal.object ("file_hash" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileFileHash obj : "message" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileMessage obj : "source" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileSource obj : "type" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileType obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("file_hash" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileFileHash obj) GHC.Base.<> (("message" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileMessage obj) GHC.Base.<> (("source" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileSource obj) GHC.Base.<> ("type" Data.Aeson.Types.ToJSON..= passportElementErrorTranslationFileType obj))))
instance Data.Aeson.Types.FromJSON.FromJSON PassportElementErrorTranslationFile
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PassportElementErrorTranslationFile" (\obj -> (((GHC.Base.pure PassportElementErrorTranslationFile GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_hash")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "message")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "source")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))
-- | Create a new 'PassportElementErrorTranslationFile' with all required fields.
mkPassportElementErrorTranslationFile :: Data.Text.Internal.Text -- ^ 'passportElementErrorTranslationFileFileHash'
  -> Data.Text.Internal.Text -- ^ 'passportElementErrorTranslationFileMessage'
  -> Data.Text.Internal.Text -- ^ 'passportElementErrorTranslationFileSource'
  -> PassportElementErrorTranslationFileType' -- ^ 'passportElementErrorTranslationFileType'
  -> PassportElementErrorTranslationFile
mkPassportElementErrorTranslationFile passportElementErrorTranslationFileFileHash passportElementErrorTranslationFileMessage passportElementErrorTranslationFileSource passportElementErrorTranslationFileType = PassportElementErrorTranslationFile{passportElementErrorTranslationFileFileHash = passportElementErrorTranslationFileFileHash,
                                                                                                                                                                                                                                                     passportElementErrorTranslationFileMessage = passportElementErrorTranslationFileMessage,
                                                                                                                                                                                                                                                     passportElementErrorTranslationFileSource = passportElementErrorTranslationFileSource,
                                                                                                                                                                                                                                                     passportElementErrorTranslationFileType = passportElementErrorTranslationFileType}
-- | Defines the enum schema located at @components.schemas.PassportElementErrorTranslationFile.properties.type@ in the specification.
-- 
-- Type of element of the user\'s Telegram Passport which has the issue, one of “passport”, “driver\\_license”, “identity\\_card”, “internal\\_passport”, “utility\\_bill”, “bank\\_statement”, “rental\\_agreement”, “passport\\_registration”, “temporary\\_registration”
data PassportElementErrorTranslationFileType' =
   PassportElementErrorTranslationFileType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PassportElementErrorTranslationFileType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PassportElementErrorTranslationFileType'EnumPassport -- ^ Represents the JSON value @"passport"@
  | PassportElementErrorTranslationFileType'EnumDriverLicense -- ^ Represents the JSON value @"driver_license"@
  | PassportElementErrorTranslationFileType'EnumIdentityCard -- ^ Represents the JSON value @"identity_card"@
  | PassportElementErrorTranslationFileType'EnumInternalPassport -- ^ Represents the JSON value @"internal_passport"@
  | PassportElementErrorTranslationFileType'EnumUtilityBill -- ^ Represents the JSON value @"utility_bill"@
  | PassportElementErrorTranslationFileType'EnumBankStatement -- ^ Represents the JSON value @"bank_statement"@
  | PassportElementErrorTranslationFileType'EnumRentalAgreement -- ^ Represents the JSON value @"rental_agreement"@
  | PassportElementErrorTranslationFileType'EnumPassportRegistration -- ^ Represents the JSON value @"passport_registration"@
  | PassportElementErrorTranslationFileType'EnumTemporaryRegistration -- ^ Represents the JSON value @"temporary_registration"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PassportElementErrorTranslationFileType'
    where toJSON (PassportElementErrorTranslationFileType'Other val) = val
          toJSON (PassportElementErrorTranslationFileType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (PassportElementErrorTranslationFileType'EnumPassport) = "passport"
          toJSON (PassportElementErrorTranslationFileType'EnumDriverLicense) = "driver_license"
          toJSON (PassportElementErrorTranslationFileType'EnumIdentityCard) = "identity_card"
          toJSON (PassportElementErrorTranslationFileType'EnumInternalPassport) = "internal_passport"
          toJSON (PassportElementErrorTranslationFileType'EnumUtilityBill) = "utility_bill"
          toJSON (PassportElementErrorTranslationFileType'EnumBankStatement) = "bank_statement"
          toJSON (PassportElementErrorTranslationFileType'EnumRentalAgreement) = "rental_agreement"
          toJSON (PassportElementErrorTranslationFileType'EnumPassportRegistration) = "passport_registration"
          toJSON (PassportElementErrorTranslationFileType'EnumTemporaryRegistration) = "temporary_registration"
instance Data.Aeson.Types.FromJSON.FromJSON PassportElementErrorTranslationFileType'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "passport" -> PassportElementErrorTranslationFileType'EnumPassport
                                            | val GHC.Classes.== "driver_license" -> PassportElementErrorTranslationFileType'EnumDriverLicense
                                            | val GHC.Classes.== "identity_card" -> PassportElementErrorTranslationFileType'EnumIdentityCard
                                            | val GHC.Classes.== "internal_passport" -> PassportElementErrorTranslationFileType'EnumInternalPassport
                                            | val GHC.Classes.== "utility_bill" -> PassportElementErrorTranslationFileType'EnumUtilityBill
                                            | val GHC.Classes.== "bank_statement" -> PassportElementErrorTranslationFileType'EnumBankStatement
                                            | val GHC.Classes.== "rental_agreement" -> PassportElementErrorTranslationFileType'EnumRentalAgreement
                                            | val GHC.Classes.== "passport_registration" -> PassportElementErrorTranslationFileType'EnumPassportRegistration
                                            | val GHC.Classes.== "temporary_registration" -> PassportElementErrorTranslationFileType'EnumTemporaryRegistration
                                            | GHC.Base.otherwise -> PassportElementErrorTranslationFileType'Other val)
