-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}

-- | Contains the default configuration
module StripeAPI.Configuration where

import qualified Data.Text
import qualified GHC.Types 
import qualified StripeAPI.Common

-- | The default url specified by the OpenAPI specification
-- 
-- @https://api.telegram.org/bot{token}@
defaultURL = Data.Text.pack "https://api.telegram.org/bot{token}"
-- | The default application name used in the @User-Agent@ header which is based on the @info.title@ field of the specification
-- 
-- @Telegram Bot API@
defaultApplicationName = Data.Text.pack "Telegram Bot API"
-- | The default configuration containing the 'defaultURL' and no authorization
defaultConfiguration = StripeAPI.Common.Configuration defaultURL StripeAPI.Common.anonymousSecurityScheme GHC.Types.True defaultApplicationName
