-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation postSendMessage
module StripeAPI.Operations.PostSendMessage where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified StripeAPI.Common
import StripeAPI.Types

-- | > POST /sendMessage
-- 
-- Use this method to send text messages. On success, the sent [Message](https:\/\/core.telegram.org\/bots\/api\/\#message) is returned.
postSendMessage :: forall m . StripeAPI.Common.MonadHTTP m => PostSendMessageRequestBody -- ^ The request body to send
  -> StripeAPI.Common.ClientT m (Network.HTTP.Client.Types.Response PostSendMessageResponse) -- ^ Monadic computation which returns the result of the operation
postSendMessage body = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either PostSendMessageResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> PostSendMessageResponse200 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                PostSendMessageResponseBody200)
                                                                                                                                                                 | GHC.Base.const GHC.Types.True (Network.HTTP.Client.Types.responseStatus response) -> PostSendMessageResponseDefault Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                  Error)
                                                                                                                                                                 | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (StripeAPI.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack "/sendMessage") GHC.Base.mempty (GHC.Maybe.Just body) StripeAPI.Common.RequestBodyEncodingJSON)
-- | Defines the object schema located at @paths.\/sendMessage.POST.requestBody.content.application\/json.schema@ in the specification.
-- 
-- 
data PostSendMessageRequestBody = PostSendMessageRequestBody {
  -- | allow_sending_without_reply: Pass *True*, if the message should be sent even if the specified replied-to message is not found
  postSendMessageRequestBodyAllowSendingWithoutReply :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | chat_id: Unique identifier for the target chat or username of the target channel (in the format \`\@channelusername\`)
  , postSendMessageRequestBodyChatId :: PostSendMessageRequestBodyChatId'Variants
  -- | disable_notification: Sends the message [silently](https:\/\/telegram.org\/blog\/channels-2-0\#silent-messages). Users will receive a notification with no sound.
  , postSendMessageRequestBodyDisableNotification :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | disable_web_page_preview: Disables link previews for links in this message
  , postSendMessageRequestBodyDisableWebPagePreview :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | entities: A JSON-serialized list of special entities that appear in message text, which can be specified instead of *parse\\_mode*
  , postSendMessageRequestBodyEntities :: (GHC.Maybe.Maybe ([MessageEntity]))
  -- | parse_mode: Mode for parsing entities in the message text. See [formatting options](https:\/\/core.telegram.org\/bots\/api\/\#formatting-options) for more details.
  , postSendMessageRequestBodyParseMode :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | protect_content: Protects the contents of the sent message from forwarding and saving
  , postSendMessageRequestBodyProtectContent :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | reply_markup: Additional interface options. A JSON-serialized object for an [inline keyboard](https:\/\/core.telegram.org\/bots\#inline-keyboards-and-on-the-fly-updating), [custom reply keyboard](https:\/\/core.telegram.org\/bots\#keyboards), instructions to remove reply keyboard or to force a reply from the user.
  , postSendMessageRequestBodyReplyMarkup :: (GHC.Maybe.Maybe PostSendMessageRequestBodyReplyMarkup')
  -- | reply_to_message_id: If the message is a reply, ID of the original message
  , postSendMessageRequestBodyReplyToMessageId :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | text: Text of the message to be sent, 1-4096 characters after entities parsing
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 4096
  -- * Minimum length of 1
  , postSendMessageRequestBodyText :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostSendMessageRequestBody
    where toJSON obj = Data.Aeson.Types.Internal.object ("allow_sending_without_reply" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyAllowSendingWithoutReply obj : "chat_id" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyChatId obj : "disable_notification" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyDisableNotification obj : "disable_web_page_preview" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyDisableWebPagePreview obj : "entities" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyEntities obj : "parse_mode" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyParseMode obj : "protect_content" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyProtectContent obj : "reply_markup" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup obj : "reply_to_message_id" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyToMessageId obj : "text" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyText obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("allow_sending_without_reply" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyAllowSendingWithoutReply obj) GHC.Base.<> (("chat_id" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyChatId obj) GHC.Base.<> (("disable_notification" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyDisableNotification obj) GHC.Base.<> (("disable_web_page_preview" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyDisableWebPagePreview obj) GHC.Base.<> (("entities" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyEntities obj) GHC.Base.<> (("parse_mode" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyParseMode obj) GHC.Base.<> (("protect_content" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyProtectContent obj) GHC.Base.<> (("reply_markup" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup obj) GHC.Base.<> (("reply_to_message_id" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyToMessageId obj) GHC.Base.<> ("text" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyText obj))))))))))
instance Data.Aeson.Types.FromJSON.FromJSON PostSendMessageRequestBody
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostSendMessageRequestBody" (\obj -> (((((((((GHC.Base.pure PostSendMessageRequestBody GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "allow_sending_without_reply")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "chat_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "disable_notification")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "disable_web_page_preview")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "entities")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "parse_mode")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "protect_content")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "reply_markup")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "reply_to_message_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "text"))
-- | Create a new 'PostSendMessageRequestBody' with all required fields.
mkPostSendMessageRequestBody :: PostSendMessageRequestBodyChatId'Variants -- ^ 'postSendMessageRequestBodyChatId'
  -> Data.Text.Internal.Text -- ^ 'postSendMessageRequestBodyText'
  -> PostSendMessageRequestBody
mkPostSendMessageRequestBody postSendMessageRequestBodyChatId postSendMessageRequestBodyText = PostSendMessageRequestBody{postSendMessageRequestBodyAllowSendingWithoutReply = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyChatId = postSendMessageRequestBodyChatId,
                                                                                                                          postSendMessageRequestBodyDisableNotification = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyDisableWebPagePreview = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyEntities = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyParseMode = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyProtectContent = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyReplyMarkup = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyReplyToMessageId = GHC.Maybe.Nothing,
                                                                                                                          postSendMessageRequestBodyText = postSendMessageRequestBodyText}
-- | Defines the oneOf schema located at @paths.\/sendMessage.POST.requestBody.content.application\/json.schema.properties.chat_id.anyOf@ in the specification.
-- 
-- Unique identifier for the target chat or username of the target channel (in the format \`\@channelusername\`)
data PostSendMessageRequestBodyChatId'Variants =
   PostSendMessageRequestBodyChatId'Int GHC.Types.Int
  | PostSendMessageRequestBodyChatId'Text Data.Text.Internal.Text
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostSendMessageRequestBodyChatId'Variants
    where toJSON (PostSendMessageRequestBodyChatId'Int a) = Data.Aeson.Types.ToJSON.toJSON a
          toJSON (PostSendMessageRequestBodyChatId'Text a) = Data.Aeson.Types.ToJSON.toJSON a
instance Data.Aeson.Types.FromJSON.FromJSON PostSendMessageRequestBodyChatId'Variants
    where parseJSON val = case (PostSendMessageRequestBodyChatId'Int Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((PostSendMessageRequestBodyChatId'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                              Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
                              Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a
-- | Defines the object schema located at @paths.\/sendMessage.POST.requestBody.content.application\/json.schema.properties.reply_markup.anyOf@ in the specification.
-- 
-- Additional interface options. A JSON-serialized object for an [inline keyboard](https:\\\/\\\/core.telegram.org\\\/bots\\\#inline-keyboards-and-on-the-fly-updating), [custom reply keyboard](https:\\\/\\\/core.telegram.org\\\/bots\\\#keyboards), instructions to remove reply keyboard or to force a reply from the user.
data PostSendMessageRequestBodyReplyMarkup' = PostSendMessageRequestBodyReplyMarkup' {
  -- | force_reply: Shows reply interface to the user, as if they manually selected the bot\'s message and tapped \'Reply\'
  postSendMessageRequestBodyReplyMarkup'ForceReply :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | inline_keyboard: Array of button rows, each represented by an Array of [InlineKeyboardButton](https:\/\/core.telegram.org\/bots\/api\/\#inlinekeyboardbutton) objects
  , postSendMessageRequestBodyReplyMarkup'InlineKeyboard :: (GHC.Maybe.Maybe ([[InlineKeyboardButton]]))
  -- | input_field_placeholder: *Optional*. The placeholder to be shown in the input field when the keyboard is active; 1-64 characters
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 64
  -- * Minimum length of 1
  , postSendMessageRequestBodyReplyMarkup'InputFieldPlaceholder :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | keyboard: Array of button rows, each represented by an Array of [KeyboardButton](https:\/\/core.telegram.org\/bots\/api\/\#keyboardbutton) objects
  , postSendMessageRequestBodyReplyMarkup'Keyboard :: (GHC.Maybe.Maybe ([[KeyboardButton]]))
  -- | one_time_keyboard: *Optional*. Requests clients to hide the keyboard as soon as it\'s been used. The keyboard will still be available, but clients will automatically display the usual letter-keyboard in the chat – the user can press a special button in the input field to see the custom keyboard again. Defaults to *false*.
  , postSendMessageRequestBodyReplyMarkup'OneTimeKeyboard :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | remove_keyboard: Requests clients to remove the custom keyboard (user will not be able to summon this keyboard; if you want to hide the keyboard from sight but keep it accessible, use *one\\_time\\_keyboard* in [ReplyKeyboardMarkup](https:\/\/core.telegram.org\/bots\/api\/\#replykeyboardmarkup))
  , postSendMessageRequestBodyReplyMarkup'RemoveKeyboard :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | resize_keyboard: *Optional*. Requests clients to resize the keyboard vertically for optimal fit (e.g., make the keyboard smaller if there are just two rows of buttons). Defaults to *false*, in which case the custom keyboard is always of the same height as the app\'s standard keyboard.
  , postSendMessageRequestBodyReplyMarkup'ResizeKeyboard :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | selective: *Optional*. Use this parameter if you want to show the keyboard to specific users only. Targets: 1) users that are \@mentioned in the *text* of the [Message](https:\/\/core.telegram.org\/bots\/api\/\#message) object; 2) if the bot\'s message is a reply (has *reply\\_to\\_message\\_id*), sender of the original message.  
  -- 
  -- *Example:* A user requests to change the bot\'s language, bot replies to the request with a keyboard to select the new language. Other users in the group don\'t see the keyboard.
  , postSendMessageRequestBodyReplyMarkup'Selective :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostSendMessageRequestBodyReplyMarkup'
    where toJSON obj = Data.Aeson.Types.Internal.object ("force_reply" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'ForceReply obj : "inline_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'InlineKeyboard obj : "input_field_placeholder" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'InputFieldPlaceholder obj : "keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'Keyboard obj : "one_time_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'OneTimeKeyboard obj : "remove_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'RemoveKeyboard obj : "resize_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'ResizeKeyboard obj : "selective" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'Selective obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("force_reply" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'ForceReply obj) GHC.Base.<> (("inline_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'InlineKeyboard obj) GHC.Base.<> (("input_field_placeholder" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'InputFieldPlaceholder obj) GHC.Base.<> (("keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'Keyboard obj) GHC.Base.<> (("one_time_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'OneTimeKeyboard obj) GHC.Base.<> (("remove_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'RemoveKeyboard obj) GHC.Base.<> (("resize_keyboard" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'ResizeKeyboard obj) GHC.Base.<> ("selective" Data.Aeson.Types.ToJSON..= postSendMessageRequestBodyReplyMarkup'Selective obj))))))))
instance Data.Aeson.Types.FromJSON.FromJSON PostSendMessageRequestBodyReplyMarkup'
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostSendMessageRequestBodyReplyMarkup'" (\obj -> (((((((GHC.Base.pure PostSendMessageRequestBodyReplyMarkup' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "force_reply")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "inline_keyboard")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "input_field_placeholder")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "keyboard")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "one_time_keyboard")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "remove_keyboard")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "resize_keyboard")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "selective"))
-- | Create a new 'PostSendMessageRequestBodyReplyMarkup'' with all required fields.
mkPostSendMessageRequestBodyReplyMarkup' :: PostSendMessageRequestBodyReplyMarkup'
mkPostSendMessageRequestBodyReplyMarkup' = PostSendMessageRequestBodyReplyMarkup'{postSendMessageRequestBodyReplyMarkup'ForceReply = GHC.Maybe.Nothing,
                                                                                  postSendMessageRequestBodyReplyMarkup'InlineKeyboard = GHC.Maybe.Nothing,
                                                                                  postSendMessageRequestBodyReplyMarkup'InputFieldPlaceholder = GHC.Maybe.Nothing,
                                                                                  postSendMessageRequestBodyReplyMarkup'Keyboard = GHC.Maybe.Nothing,
                                                                                  postSendMessageRequestBodyReplyMarkup'OneTimeKeyboard = GHC.Maybe.Nothing,
                                                                                  postSendMessageRequestBodyReplyMarkup'RemoveKeyboard = GHC.Maybe.Nothing,
                                                                                  postSendMessageRequestBodyReplyMarkup'ResizeKeyboard = GHC.Maybe.Nothing,
                                                                                  postSendMessageRequestBodyReplyMarkup'Selective = GHC.Maybe.Nothing}
-- | Represents a response of the operation 'postSendMessage'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'PostSendMessageResponseError' is used.
data PostSendMessageResponse =
   PostSendMessageResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | PostSendMessageResponse200 PostSendMessageResponseBody200 -- ^ 
  | PostSendMessageResponseDefault Error -- ^ 
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | Defines the object schema located at @paths.\/sendMessage.POST.responses.200.content.application\/json.schema@ in the specification.
-- 
-- 
data PostSendMessageResponseBody200 = PostSendMessageResponseBody200 {
  -- | ok
  postSendMessageResponseBody200Ok :: GHC.Types.Bool
  -- | result: This object represents a message.
  , postSendMessageResponseBody200Result :: Message
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostSendMessageResponseBody200
    where toJSON obj = Data.Aeson.Types.Internal.object ("ok" Data.Aeson.Types.ToJSON..= postSendMessageResponseBody200Ok obj : "result" Data.Aeson.Types.ToJSON..= postSendMessageResponseBody200Result obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("ok" Data.Aeson.Types.ToJSON..= postSendMessageResponseBody200Ok obj) GHC.Base.<> ("result" Data.Aeson.Types.ToJSON..= postSendMessageResponseBody200Result obj))
instance Data.Aeson.Types.FromJSON.FromJSON PostSendMessageResponseBody200
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostSendMessageResponseBody200" (\obj -> (GHC.Base.pure PostSendMessageResponseBody200 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "ok")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "result"))
-- | Create a new 'PostSendMessageResponseBody200' with all required fields.
mkPostSendMessageResponseBody200 :: GHC.Types.Bool -- ^ 'postSendMessageResponseBody200Ok'
  -> Message -- ^ 'postSendMessageResponseBody200Result'
  -> PostSendMessageResponseBody200
mkPostSendMessageResponseBody200 postSendMessageResponseBody200Ok postSendMessageResponseBody200Result = PostSendMessageResponseBody200{postSendMessageResponseBody200Ok = postSendMessageResponseBody200Ok,
                                                                                                                                        postSendMessageResponseBody200Result = postSendMessageResponseBody200Result}
